component_version: 1.0.0
maximum_availability_zones: 5

metric_name: VulnerableImageCount
metric_namespace: Clair

include_klar: true

lambdas:
  distribution:
    bucket:
      Ref: S3Bucket
    prefix: lambdas

  functions:
    stackcollector:
      handler: handler.lambda_handler
      runtime: python3.6
      code_uri: stack-collector/handler.zip
      timeout: 30
      environment:
        ACCOUNT_ID:
          Ref: AWS::AccountId
        TARGET_FUNCTION_ARN:
          Fn::GetAtt: [imagecollector, Arn]
        STACKS:
          Ref: Stacks
      policies:
        logs:
          Action:
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
          Resource:
            - '*'
        lambda:
          Action:
            - lambda:Invoke
          Resource:
            - '*'
      log_retention: 14
      events:
        cron:
          type: schedule
          expression: rate(12 hours)

    imagecollector:
      handler: handler.lambda_handler
      runtime: python3.6
      code_uri: image-collector/handler.zip
      timeout: 60
      environment:
        ACCOUNT_ID:
          Ref: AWS::AccountId
        TASK_DEFINITION_ARN:
          Ref: TaskDefinition
        ECS_CLUSTER:
          Ref: Cluster
      policies:
        logs:
          Action:
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
          Resource:
            - '*'
        lambda:
          Action:
            - lambda:Invoke
          Resource:
            - '*'
        cloudformation:
          Action:
            - cloudformation:DescribeStackResources
          Resource:
            - '*'
        ecs:
          Action:
            - ecs:DescribeTaskDefinition
            - ecs:RunTask
          Resource:
            - '*'
      log_retention: 14

    logstosns:
      handler: handler.lambda_handler
      runtime: python3.6
      code_uri: logs-to-sns/handler.zip
      timeout: 30
      environment:
        NOTIFY_SNS:
          TODO # TODO
      policies:
        logs:
          Action:
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
          Resource:
            - '*'
        lambda:
          Action:
            - lambda:Invoke
          Resource:
            - '*'
      log_retention: 14
      events:
        Topic:
          type: sns
